apiVersion: v1
kind: Namespace
metadata:
  name: app-ns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: us-docker.pkg.dev/spanner-gke-443910/spanner-game-images/payment-service:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reconciliation-service
  namespace: app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reconciliation-service
  template:
    metadata:
      labels:
        app: reconciliation-service
    spec:
      containers:
      - name: reconciliation-service
        image: us-docker.pkg.dev/spanner-gke-443910/spanner-game-images/reconciliation-service:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
      - name: transaction-service
        image: us-docker.pkg.dev/spanner-gke-443910/spanner-game-images/transaction-service:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-1
  labels:
    app: payment-service-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service-1
  template:
    metadata:
      labels:
        app: payment-service-1
    spec:
      containers:
        - name: payment-service-1
          image: us-docker.pkg.dev/spanner-gke-443910/spanner-game-images/payment-service-1:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPANNER_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: payment-service-1-config
                  key: SPANNER_PROJECT_ID
            - name: SPANNER_INSTANCE_ID
              valueFrom:
                configMapKeyRef:
                  name: payment-service-1-config
                  key: SPANNER_INSTANCE_ID
            - name: SPANNER_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: payment-service-1-config
                  key: SPANNER_DATABASE_NAME
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30 # Wait time before readiness check starts
            periodSeconds: 10       # How often to perform the check
            failureThreshold: 3     # Number of failures before marking as not ready
            successThreshold: 1     # Number of successes before marking as ready
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30 # Wait time before liveness check starts
            periodSeconds: 10       # How often to perform the check
            failureThreshold: 5     # Number of failures before restarting the container
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service-1
  labels:
    app: payment-service-1
spec:
  type: ClusterIP
  selector:
    app: payment-service-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-1-config
data:
  SPANNER_PROJECT_ID: spanner-gke-443910
  SPANNER_INSTANCE_ID: sample-instance
  SPANNER_DATABASE_NAME: sample-database
