---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: us-docker.pkg.dev/spanner-gke-443910/spanner-game-images/payment-service:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        env:
          - name: SPANNER_PROJECT_ID
            valueFrom:
              configMapKeyRef:
                name: payment-service-config
                key: SPANNER_PROJECT_ID
          - name: SPANNER_INSTANCE_ID
            valueFrom:
              configMapKeyRef:
                name: payment-service-config
                key: SPANNER_INSTANCE_ID
          - name: SPANNER_DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: payment-service-config
                key: SPANNER_DATABASE_NAME
          - name: AUDIT_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: payment-service-config
                key: AUDIT_DB_NAME
          - name: PAYMENT_AUDIT_TABLE
            valueFrom:
              configMapKeyRef:
                name: payment-service-config
                key: PAYMENT_AUDIT_TABLE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reconciliation-service
  namespace: app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reconciliation-service
  template:
    metadata:
      labels:
        app: reconciliation-service
    spec:
      containers:
      - name: reconciliation-service
        image: us-docker.pkg.dev/spanner-gke-443910/spanner-game-images/reconciliation-service:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        env:
          - name: SPANNER_PROJECT_ID
            valueFrom:
              configMapKeyRef:
                name: reconciliation-service-config
                key: SPANNER_PROJECT_ID
          - name: SPANNER_INSTANCE_ID
            valueFrom:
              configMapKeyRef:
                name: reconciliation-service-config
                key: SPANNER_INSTANCE_ID
          - name: SPANNER_DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: reconciliation-service-config
                key: SPANNER_DATABASE_NAME
          - name: AUDIT_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: reconciliation-service-config
                key: AUDIT_DB_NAME
          - name: RECONCILIATION_AUDIT_TABLE
            valueFrom:
              configMapKeyRef:
                name: reconciliation-service-config
                key: RECONCILIATION_AUDIT_TABLE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
      - name: transaction-service
        image: us-docker.pkg.dev/spanner-gke-443910/spanner-game-images/transaction-service:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        env:
          - name: SPANNER_PROJECT_ID
            value: spanner-gke-443910
          - name: SPANNER_INSTANCE_ID
            value: sample-instance
          - name: SPANNER_DATABASE_NAME
            value: shared-db
          - name: AUDIT_DB_NAME
            value: audit-db  # New audit database
          - name: TRANSACTION_AUDIT_TABLE
            value: transaction_audit_trail  # Table for audit logs

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: app-ns
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: reconciliation-service
  namespace: app-ns
  labels:
    app: reconciliation-service
spec:
  selector:
    app: reconciliation-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: app-ns
  labels:
    app: transaction-service
spec:
  selector:
    app: transaction-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
