apiVersion: v1
kind: Namespace
metadata:
  name: app-ns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: us-docker.pkg.dev/spanner-gke-443910/spanner-game-images/payment-service:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reconciliation-service
  namespace: app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reconciliation-service
  template:
    metadata:
      labels:
        app: reconciliation-service
    spec:
      containers:
      - name: reconciliation-service
        image: us-docker.pkg.dev/spanner-gke-443910/spanner-game-images/reconciliation-service:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
      - name: transaction-service
        image: us-docker.pkg.dev/spanner-gke-443910/spanner-game-images/transaction-service:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
