apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: app-ns
data:
  SPANNER_PROJECT_ID: spanner-gke-443910
  SPANNER_INSTANCE_ID: sample-instance
  SPANNER_DATABASE_NAME: shared-db
  AUDIT_DB_NAME: audit-db
  PAYMENT_AUDIT_TABLE: payment_audit_trail
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: reconciliation-service-config
  namespace: app-ns
data:
  SPANNER_PROJECT_ID: spanner-gke-443910
  SPANNER_INSTANCE_ID: sample-instance
  SPANNER_DATABASE_NAME: shared-db
  AUDIT_DB_NAME: audit-db
  RECONCILIATION_AUDIT_TABLE: reconciliation_audit_trail

