apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-spanner-job
  namespace: app-ns
spec:
  template:
    spec:
      serviceAccountName: ksa-liquibase   # KSA to be used with Workload Identity
      restartPolicy: Never
      containers:
        - name: liquibase
          image: your-registry/liquibase-job:latest  # Replace with your Liquibase image
          envFrom:
            - configMapRef:
                name: liquibase-config        # Load values from the ConfigMap
          env:
            - name: LIQUIBASE_URL
              value: >-
                jdbc:cloudspanner://$(SPANNER_PROJECT_ID)/$(SPANNER_INSTANCE_ID)/$(SPANNER_DATABASE_NAME)
          args:
            - "--url=$(LIQUIBASE_URL)"
            - "--changeLogFile=$(LIQUIBASE_CHANGELOG_FILE)"
            - "update"
